name: 01 - building blocks

on:
 workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello World!"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: successful step
        run: |
          echo "I will succeed"
          exit 0
      - name: say bye
        run: echo "Bye!"
