name: 02 - workflow events

on:
  pull_request:
  workflow_dispatch: 

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: show the trigger
        run: echo "Trigger by ${{ github.event_name }} event"
