name: 04 - using actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
      - name: Install Dependencies
        run: ls -l
        working-directory: 04-using-actions/react-app
      - name: Install Dependencies-2
        working-directory: 04-using-actions/react-app
        run: ls -l