name: 07 - using expressions

run-name: 07 - using expression DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}

on:
  workflow_dispatch:
    inputs:
      debug:
        description: debug option
        type: boolean
        default: false

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: "[ debug ] Print debug information"
        if: ${{ inputs.debug }}
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Runner OS: ${{ runner.os }}"
      - name: '[ debug ] Print when triggered from main'
        if: ${{ inputs.debug && github.ref == 'refs/heads/main'}}
        run: echo "Triggered from main"
      - name: Greeting
        run: echo "Hello Wrold"