name: 09 - functions

on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: sleep 10 sec
        run: sleep 10

      - name: Fail step
        run: exit 1

      - name: I will be skipped
        if: ${{ success() }}
        run: echo "I will print if previous step succeed"

      - name: I will execute
        if: ${{ failure() }}
        run: echo "I will print if previous step fails"

      - name: I will execute
        if: ${{ !cancelled() }}
        run: echo "I will always print, except when the workflow is cancelled"

      - name: I will execute when cancelled
        if: ${{ cancelled() }}
        run: echo "I will print if the workflow has been cancelled"