name: 10 - execution - flow

on:
  workflow_dispatch:
    inputs:
      pass-unit-tests:
        description: Whether unit tests will pass or not
        type: boolean
        default: true

jobs:
  lint-builds:
    runs-on: ubuntu-latest
    steps:
      - name: Lint-build step
        run: echo "lint-build step running"

  unit-tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Running unit test
        run: echo "Running unit test"
      - name: Failing test
        if: ${{ !inputs.pass-unit-tests }}
        run: exit 1

  deploy-noprod:
    runs-on: ubuntu-latest
    needs: 
      - lint-builds
      - unit-tests
    steps:
      - name: Deploy to nonprod
        run: echo "Deploy to nonprod"

  e2e-tests:
    runs-on: ubuntu-latest
    needs:
      - deploy-noprod
    steps:
      - name: running E2E test
        run: echo "Running E2E test"

  load-tests:
    runs-on: ubuntu-latest
    needs:
      - deploy-noprod
    steps:
      - name: running load tests
        run: echo "Running load test"

  deploy-prod:
    runs-on: ubuntu-latest
    needs:
      - e2e-tests
      - load-tests
    steps:
      - name: Deploy to Prod
        run: echo "Deploy to Prod"