name: 16 - 2 - Working with Environment

on:
  workflow_dispatch:
    

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Deploy on Staging
        run: echo "Deploying on Staging"
  
  e2e-test:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: E2E test
        run: echo "Running E2E"
  
  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: e2e-test
    steps:
      - name: Deploy on Prod
        run: echo "Deploying on Prod"