name: 17 - 1 - custom actions - composite

run-name: 17 - 1 - custom actions - composite | env - ${{ inputs.target-env }}

on:
  workflow_dispatch:
    inputs:
      target-env:
        description: enviroment target for dependency installation
        type: choice
        options:
          - dev
          - prod
        default: dev
          

env:
  working-directory: 17-custom-actions/react-app


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node and NPM dependencies
        uses: ./.github/actions/composite-cache
        with:
          node-version: 20.x
          working-dir: ${{ env.working-directory }}
          target-env: ${{ inputs.target-env }}

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build