name: 17 - 1 - custom actions - composite

on:
  workflow_dispatch:

env:
  working-directory: 17-custom-actions/react-app


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node and NPM dependencies
        uses: ./.github/actions/composite-cache
        with:
          node-version: 20.x
          working-dir: ${{ env.working-directory }}

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build