name: 18 - 1 Reusable workflow | Reusable defination

on:
  workflow_call:
    inputs:
      target-dir:
        description: Define the target directory
        required: true
        type: string
      url:
        description: URL
        type: string
        required: true
    outputs:
      output-build-status:
        description: show the build status
        value: ${{ jobs.deploy.outputs.build-status }}
      output-url:
        description: show the output url
        value: ${{ jobs.deploy.outputs.url }}


jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.build-status }}
      url: ${{ steps.url.outputs.URL }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build Image
        id: build
        run: |
          echo "Building the Images ${{ inputs.target-dir }}"
          echo "build-status=success" >> "$GITHUB_OUTPUT"
        
      - name: show the URL
        id: url
        run: |
          echo "Show the URL"
          echo "URL=${{ inputs.url }}" >> "$GITHUB_OUTPUT"